### ISSUE TITLE
[Bug][Suggestion] Unit Property of pre-placed unit is not working

### ISSUE THREAD

**Issue by Chromowolf** [TheNitesWhoSay/Chkdraft#191]
Set the unit property of a specific preplaced unit to "50% life":
![image](https://github.com/user-attachments/assets/bfc55fbb-64aa-413f-a71c-a8c605a28e6e)

It's still 40/40 in game:
![image](https://github.com/user-attachments/assets/bb8005cc-25e4-4345-93f7-96daf5901658)

Same for resouce amount, the change of resource amount is not taking effect in-game.

I guess you have disabled all the flags including "HP is valid" flag of offset +14 for each unit in the UNIT section by default:
![image](https://github.com/user-attachments/assets/01208f4a-6e29-4c1a-862a-f0a76c272212)

I would suggest putting these flags visible in the individual unit setting interface.

**Comment by TheNitesWhoSay** [comment]
Fixed in [release 1.07](https://github.com/TheNitesWhoSay/Chkdraft/releases/tag/1.07) ; I also took a detour and made the advanced tab for unit properties which can see/edit these flags (I would have tabled that but it was useful for debugging the major issue, and might as well finish the whole thing if starting to create the UI)
