### ISSUE TITLE
[Bug] UI glitch: Main window loses focus when closing sub window

### ISSUE THREAD

**Issue by Chromowolf** [TheNitesWhoSay/Chkdraft#192]
Open the unit settings window and change any settings:
![image](https://github.com/user-attachments/assets/f8434ce4-2f0d-4b2c-83ae-c64d3dc4ee15)

Then close the unit settings window. This will result in the main chkd window being minized / lost focus.

**Comment by TheNitesWhoSay** [comment]
I don't have this *exact* issue, what I can reproduce is opening settings, focusing a window other than chkdraft, then going back and closing settings and chkdraft will lose focus to that other window; without focusing some other window focus reverts to the main window; for that the fix is easy enough & will be in next version.

**Comment by TheNitesWhoSay** [comment]
I believe this is resolved as of [release 1.07](https://github.com/TheNitesWhoSay/Chkdraft/releases/tag/1.07); you may want to check this as well.
